---
title: "Lab 2 - Data wrangling"
author: "Kathrine Marattil"
date: "Feb 10, 2026"
format: 
  html: default # for speed
  pdf: default # for final output
---

```{r}
#| eval: true
#| message: false

library(tidyverse)
```

# Questions

## Part 1

```{r}
library(tidyverse)
```

### Question 1

```{r}
midwest |>
 count(state)|>
  arrange(desc(n)) #arrange by number of counties

```

Illinois has the greatest amount of counties of 102, and Wisconsin has lowest amount of counties 72.

\newpage

### Question 2

```{r}

midwest |>
  count(county)|>
  filter(n ==5)
  
```

\newpage

### Question 3

```{r}
#a
popden <- midwest|>
  filter(popdensity > 25000)|>
  select(county, state, popdensity, poptotal, area)
popden
```

```{r}
#b
highest_popden <- midwest|>
  filter(popdensity == max(popdensity)) |>
  select(county, state, popdensity, poptotal, area)
highest_popden
```

```{}
```

\newpage

### Question 5

\newpage

### Question 6

\newpage

### Question 7

\newpage

### Question 8

\newpage

## Part 2

### Question 9
